version: '3'
services:

  siat-db:
    image: "postgres:13.3"
    container_name: siat-db
    volumes:
        - siat-data:/var/lib/postgresql/data
    ports:
        - 5432
    environment:
        POSTGRES_DB: 'siat-tec'
        POSTGRES_USER: 'siat'
        POSTGRES_PASSWORD: 'testpass'

  siat-api:
    image: "vini24/siat-tec:api"
    container_name: siat-api
    environment:
        - DB_HOST=siat-db
    ports:
        - 8000:8000
    links:
        - siat-db

  siat-client:
    build: ./client
    container_name: siat-client
    restart: always
    volumes:
        - ./nginx/config/conf.d/prod:/etc/nginx/conf.d
        - letsencrypt:/etc/letsencrypt
    ports:
        - 80:80
        - 443:443
    links:
        - siat-api

volumes:
    siat-data:
    letsencrypt: